esphome:
  name: esp32-eltek-can

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  # - ssid: !secret wifi_ssid_garage
    # password: !secret wifi_password

api:
ota:

logger:
  level: DEBUG
  
# mqtt:
   # broker: 192.168.0.102

canbus:
  - platform: esp32_can
    rx_pin: GPIO19
    tx_pin: GPIO18
    can_id: 1
    id: eltek
    use_extended_id: true
    bit_rate: 125kbps
    on_frame:
    # - can_id: 0x05014400
      # use_extended_id: true
      # then:
      # - lambda: |-
          # ESP_LOGI("main", "received can id: 0x05002038 ACK");
          # ESP_LOGI("main", "b0 = %02x", x[0]);
          # ESP_LOGI("main", "b1 = %02x", x[1]);
          # ESP_LOGI("main", "b2 = %02x", x[2]);
          # ESP_LOGI("main", "b3 = %02x", x[3]);
          # ESP_LOGI("main", "b4 = %02x", x[4]);
          # ESP_LOGI("main", "b5 = %02x", x[5]);
          # ESP_LOGI("main", "b6 = %02x", x[6]);
          # ESP_LOGI("main", "b7 = %02x", x[7]);

    - can_id: 0x05014004
      use_extended_id: true
      then:
      - lambda: |-
          ESP_LOGI("main", "received can id: 0x0501400 ACK");
          ESP_LOGI("main", "temp inlet = %d °C", x[0]);
          ESP_LOGI("main", "temp outlet = %d °C", x[7]);
          ESP_LOGI("main", "input voltage = %d V", 256*x[6]+x[5]);
          ESP_LOGI("main", "output voltage = %.2f V", (256*x[4]+x[3]) / 100.0 );
          ESP_LOGI("main", "output current = %d A", 256*x[2]+x[1]);

interval:
  - interval: 1s
    then:
          - canbus.send:
              use_extended_id: true
              can_id: 0x05004804
              canbus_id: eltek
              data: [0x06, 0x31, 0x71, 0x01, 0x60, 0x38, 0x00, 0x00]
          - canbus.send:
              use_extended_id: true
              can_id: 0x05FF4004
              canbus_id: eltek
              data: [0xA0, 0x00, 0x40, 0x15, 0x40, 0x15, 0xE0, 0x15]
          - canbus.send:
              use_extended_id: true
              can_id: 0x05004804
              canbus_id: eltek
              data: [0x06, 0x31, 0x71, 0x01, 0x60, 0x38, 0x00, 0x00]
          - canbus.send:
              use_extended_id: true
              can_id: 0x05019C00
              canbus_id: eltek
              data: [0x29, 0x15, 0x00, 0x40, 0x15, 0x00, 0x00, 0x00]